#include "Words.h"


CArrayChars gacArchaicWords;


//////////////////////////////////////////////////////////////////////////
//
//
//////////////////////////////////////////////////////////////////////////
void WordsInit(void)
{
	gacArchaicWords.Init();
	gacArchaicWords.Add("abroad: out of doors");
	gacArchaicWords.Add("accouchement: birthing");
	gacArchaicWords.Add("advertisement: a notice to readers in a book");
	gacArchaicWords.Add("afeard / afeared: frightened");
	gacArchaicWords.Add("affright: frighten(someone)");
	gacArchaicWords.Add("ague: malaria or a similar illness");
	gacArchaicWords.Add("aliment: food; nourishment");
	gacArchaicWords.Add("ambuscade: an ambush");
	gacArchaicWords.Add("animalcule: a microscopic animal");
	gacArchaicWords.Add("apothecary: a person who prepared and sold medicine");
	gacArchaicWords.Add("appetency: a longing or desire");
	gacArchaicWords.Add("assay: attempt");
	gacArchaicWords.Add("asunder: apart");
	gacArchaicWords.Add("audition: the power of hearing");
	gacArchaicWords.Add("aught: anything at all");
	gacArchaicWords.Add("avaunt: go away");
	gacArchaicWords.Add("bane: poison");
	gacArchaicWords.Add("baseborn: of low birth or social standing");
	gacArchaicWords.Add("bedlam: an asylum");
	gacArchaicWords.Add("behold: see or observe");
	gacArchaicWords.Add("behoof: benefit or advantage");
	gacArchaicWords.Add("beldam: an old woman");
	gacArchaicWords.Add("bethink oneself of: remember; recollect");
	gacArchaicWords.Add("betimes: in good time; early");
	gacArchaicWords.Add("bibliopole: a dealer in books");
	gacArchaicWords.Add("bijoux: jewellery; trinkets");
	gacArchaicWords.Add("billow: a large sea wave");
	gacArchaicWords.Add("blackguard: a scoundrel");
	gacArchaicWords.Add("blow: produce flowers or be in flower");
	gacArchaicWords.Add("bodkin: a dagger");
	gacArchaicWords.Add("bootless(of a task) ineffectual; useless");
	gacArchaicWords.Add("breech: a person's buttocks");
	gacArchaicWords.Add("bridewell: a prison or reform school for petty offenders");
	gacArchaicWords.Add("brimstone: sulphur");
	gacArchaicWords.Add("bruit: a report or rumour");
	gacArchaicWords.Add("buck: a fashionable and daring young man");
	gacArchaicWords.Add("bumper: a generous glass of an alcoholic drink");
	gacArchaicWords.Add("burgess: a full citizen of a town or borough");
	gacArchaicWords.Add("buss: a kiss");
	gacArchaicWords.Add("caboose: a kitchen on a ship's deck");
	gacArchaicWords.Add("cadet: a younger son or daughter");
	gacArchaicWords.Add("caducity: the infirmity of old age; senility");
	gacArchaicWords.Add("camelopard: a giraffe");
	gacArchaicWords.Add("cannonade: bombard");
	gacArchaicWords.Add("carl: a man of low birth");
	gacArchaicWords.Add("ceil: line or plaster the roof of(a building)");
	gacArchaicWords.Add("champaign: open level countryside");
	gacArchaicWords.Add("chapman: a peddler");
	gacArchaicWords.Add("chicane: deceive; hoodwink");
	gacArchaicWords.Add("circumjacent: surrounding");
	gacArchaicWords.Add("cicisbeo: a married woman's male companion or lover");
	gacArchaicWords.Add("cispontine: on the north side of the Thames in London");
	gacArchaicWords.Add("cleanse: restore to health");
	gacArchaicWords.Add("clerk: a literate or scholarly person");
	gacArchaicWords.Add("clew: a ball of thread");
	gacArchaicWords.Add("clout: a piece of cloth or clothing");
	gacArchaicWords.Add("collogue: talk confidentially");
	gacArchaicWords.Add("commend: entrust someone or something to");
	gacArchaicWords.Add("commons: provisions shared in common; rations");
	gacArchaicWords.Add("communicant: a person who imparts information");
	gacArchaicWords.Add("compass: encircle or surround");
	gacArchaicWords.Add("compeer: a companion or close associate");
	gacArchaicWords.Add("con: study attentively or learn by heart(a piece of writing)");
	gacArchaicWords.Add("condition: social position");
	gacArchaicWords.Add("conjure: implore(someone) to do something");
	gacArchaicWords.Add("contemn: treat or regard with contempt");
	gacArchaicWords.Add("contumely: insolent or insulting language or treatment");
	gacArchaicWords.Add("cordwainer: a shoemaker");
	gacArchaicWords.Add("corrupt: rotten or putrid");
	gacArchaicWords.Add("corse: a corpse");
	gacArchaicWords.Add("cottier: a rural labourer living in a cottage");
	gacArchaicWords.Add("coxcomb: a vain and conceited man; a dandy");
	gacArchaicWords.Add("coz: cousin");
	gacArchaicWords.Add("crinkum - crankum: elaborate decoration or detail");
	gacArchaicWords.Add("crookback: a person with a hunchback");
	gacArchaicWords.Add("crumpet: a person's head");
	gacArchaicWords.Add("cruse: an earthenware pot or jar");
	gacArchaicWords.Add("cully: a friendly form of address for a man");
	gacArchaicWords.Add("cutpurse: a pickpocket");
	gacArchaicWords.Add("dame: an elderly or mature woman");
	gacArchaicWords.Add("damsel: a young unmarried woman");
	gacArchaicWords.Add("dandiprat: a young or insignificant person");
	gacArchaicWords.Add("darbies: handcuffs");
	gacArchaicWords.Add("dark: ignorant");
	gacArchaicWords.Add("degrade: reduce to a lower rank, especially as a punishment");
	gacArchaicWords.Add("degree: social or official rank");
	gacArchaicWords.Add("delate: report(an offence)");
	gacArchaicWords.Add("demesne: a region or domain");
	gacArchaicWords.Add("demit: resign from(an office or position)");
	gacArchaicWords.Add("demoralize: corrupt the morals of");
	gacArchaicWords.Add("dight: clothed or equipped");
	gacArchaicWords.Add("discover: divulge(a secret)");
	gacArchaicWords.Add("disport: frolic");
	gacArchaicWords.Add("dispraise: censure or criticize");
	gacArchaicWords.Add("divers: of varying types; several");
	gacArchaicWords.Add("doit: a very small amount of money");
	gacArchaicWords.Add("dot: a dowry from which only the interest or annual income was available to the husband");
	gacArchaicWords.Add("doxy: a lover or mistress");
	gacArchaicWords.Add("drab: a slovenly woman");
	gacArchaicWords.Add("drought: thirst");
	gacArchaicWords.Add("egad: exclamation of surprise, anger, or affirmation");
	gacArchaicWords.Add("embarrass: hamper or impede");
	gacArchaicWords.Add("embouchure: the mouth of a river");
	gacArchaicWords.Add("equipage: gear; equipment");
	gacArchaicWords.Add("ere: before(in time)");
	gacArchaicWords.Add("espousal: a marriage or engagement");
	gacArchaicWords.Add("estate: a particular state, period, or condition in life");
	gacArchaicWords.Add("esurient: hungry");
	gacArchaicWords.Add("expectations: one's prospects of inheritance");
	gacArchaicWords.Add("expiry: death");
	gacArchaicWords.Add("fain: pleased or willing under the circumstances");
	gacArchaicWords.Add("fainéant: an idle or ineffective person");
	gacArchaicWords.Add("fair: beautiful");
	gacArchaicWords.Add("fandangle: a useless or purely ornamental thing");
	gacArchaicWords.Add("fane: a shrine or temple");
	gacArchaicWords.Add("fare: travel");
	gacArchaicWords.Add("fell: an animal skin; a pelt");
	gacArchaicWords.Add("feminal: feminine; womanly");
	gacArchaicWords.Add("fervent: hot or glowing");
	gacArchaicWords.Add("fie: exclamation used to express disgust or outrage");
	gacArchaicWords.Add("filibeg: a kilt");
	gacArchaicWords.Add("fishwife: a woman who sells fish");
	gacArchaicWords.Add("fizgig: a silly or flirtatious young woman");
	gacArchaicWords.Add("flux: diarrhoea or dysentery");
	gacArchaicWords.Add("forfend: avert or prevent(something evil or unpleasant)");
	gacArchaicWords.Add("forsooth: indeed");
	gacArchaicWords.Add("fourscore: eighty");
	gacArchaicWords.Add("freak: a whim");
	gacArchaicWords.Add("frore: frozen or frosty");
	gacArchaicWords.Add("froward(of a person) difficult to deal with; contrary");
	gacArchaicWords.Add("fruit: offspring");
	gacArchaicWords.Add("fudge: nonsense");
	gacArchaicWords.Add("furbish: polish(a weapon)");
	gacArchaicWords.Add("gadzooks: an expression of surprise or annoyance");
	gacArchaicWords.Add("gage: a valued object deposited as a guarantee");
	gacArchaicWords.Add("gallant: a dashing gentleman");
	gacArchaicWords.Add("gammer: an old woman");
	gacArchaicWords.Add("garland: a literary anthology");
	gacArchaicWords.Add("garth: a yard or garden");
	gacArchaicWords.Add("gaud: a trinket");
	gacArchaicWords.Add("gentle: noble or courteous");
	gacArchaicWords.Add("glabriety: baldness");
	gacArchaicWords.Add("glaciate: freeze over");
	gacArchaicWords.Add("glebe: a meadow");
	gacArchaicWords.Add("glim: a candle");
	gacArchaicWords.Add("go - cart: a baby walker");
	gacArchaicWords.Add("God's acre: a churchyard");
	gacArchaicWords.Add("goodly: attractive, excellent, or virtuous");
	gacArchaicWords.Add("goody(with a name) an elderly woman of humble position");
	gacArchaicWords.Add("grateful: received with gratitude");
	gacArchaicWords.Add("greenwood: a forest");
	gacArchaicWords.Add("grimalkin: a cat");
	gacArchaicWords.Add("gudgeon: a credulous person");
	gacArchaicWords.Add("guerdon: a reward");
	gacArchaicWords.Add("gyve: a fetter or shackle");
	gacArchaicWords.Add("habiliment: clothing");
	gacArchaicWords.Add("halt: lame");
	gacArchaicWords.Add("handmaid: a female servant");
	gacArchaicWords.Add("hearken: listen");
	gacArchaicWords.Add("hence: from here");
	gacArchaicWords.Add("herbary: a herb garden");
	gacArchaicWords.Add("hereat: as a result of this");
	gacArchaicWords.Add("hereunto: to this document");
	gacArchaicWords.Add("hereupon: after or as a result of this");
	gacArchaicWords.Add("hie: go quickly");
	gacArchaicWords.Add("hight: named");
	gacArchaicWords.Add("hither: to or toward this place");
	gacArchaicWords.Add("hoar: frost");
	gacArchaicWords.Add("horse - coper: a person who deals in horses");
	gacArchaicWords.Add("horseless carriage: a car");
	gacArchaicWords.Add("host: an army");
	gacArchaicWords.Add("howbeit: nevertheless");
	gacArchaicWords.Add("husbandman: a farmer");
	gacArchaicWords.Add("immedicable: untreatable");
	gacArchaicWords.Add("imminent: overhanging");
	gacArchaicWords.Add("indite: write; compose");
	gacArchaicWords.Add("inscribe: enter the name of(someone) on a list");
	gacArchaicWords.Add("in sooth: actually");
	gacArchaicWords.Add("intelligence: news");
	gacArchaicWords.Add("intelligencer: a person who gathers intelligence");
	gacArchaicWords.Add("invest: surround(a place) in order to besiege or blockade it");
	gacArchaicWords.Add("iron horse: a steam locomotive");
	gacArchaicWords.Add("izzard: the letter Z");
	gacArchaicWords.Add("jade: a bad - tempered or disreputable woman");
	gacArchaicWords.Add("jakes: an outdoor toilet");
	gacArchaicWords.Add("job: turn a public office or a position of trust to private advantage");
	gacArchaicWords.Add("kickshaw: a fancy but insubstantial cooked dish");
	gacArchaicWords.Add("kine: cows collectively");
	gacArchaicWords.Add("kirtle: a woman's gown or a man's tunic");
	gacArchaicWords.Add("knave: a dishonest or unscrupulous man");
	gacArchaicWords.Add("larcener: thief");
	gacArchaicWords.Add("latchet: a narrow thong or lace for fastening a shoe or sandal");
	gacArchaicWords.Add("laud: praise");
	gacArchaicWords.Add("laver: a basin or similar container used for washing oneself");
	gacArchaicWords.Add("learn: teach");
	gacArchaicWords.Add("leech: a doctor or healer");
	gacArchaicWords.Add("leman: a lover or sweetheart");
	gacArchaicWords.Add("let: hinder");
	gacArchaicWords.Add("levant: abscond leaving unpaid debts");
	gacArchaicWords.Add("Levant: the eastern part of the Mediterranean");
	gacArchaicWords.Add("levy: a body of enlisted troops");
	gacArchaicWords.Add("lief: as happily; as gladly");
	gacArchaicWords.Add("like enough: probably");
	gacArchaicWords.Add("loathly: repulsive");
	gacArchaicWords.Add("lordling: a minor lord");
	gacArchaicWords.Add("love apple: a tomato");
	gacArchaicWords.Add("Lucifer: a match");
	gacArchaicWords.Add("lurdan: an idle or incompetent person");
	gacArchaicWords.Add("lying - in: seclusion before and after childbirth");
	gacArchaicWords.Add("magdalen: a reformed prostitute");
	gacArchaicWords.Add("mage: a magician or learned person");
	gacArchaicWords.Add("magnify: glorify; extol");
	gacArchaicWords.Add("maid: a girl or young woman");
	gacArchaicWords.Add("malapert: presumptuous and impudent");
	gacArchaicWords.Add("malison: a curse");
	gacArchaicWords.Add("man - at - arms: a soldier");
	gacArchaicWords.Add("marry: an expression of surprise, indignation, or emphatic assertion");
	gacArchaicWords.Add("mayhap: perhaps; possibly");
	gacArchaicWords.Add("mazed: bewildered");
	gacArchaicWords.Add("measure: a dance");
	gacArchaicWords.Add("meat: food of any kind");
	gacArchaicWords.Add("mechanical: a manual worker");
	gacArchaicWords.Add("meet: suitable or proper");
	gacArchaicWords.Add("melodist: a singer");
	gacArchaicWords.Add("methinks: it seems to me");
	gacArchaicWords.Add("moil: drudgery");
	gacArchaicWords.Add("mooncalf: a foolish person");
	gacArchaicWords.Add("morrow, the: the following day");
	gacArchaicWords.Add("mummer: an actor in the theatre");
	gacArchaicWords.Add("natheless: nevertheless");
	gacArchaicWords.Add("natural: a person born with impaired intelligence");
	gacArchaicWords.Add("naught: nothing");
	gacArchaicWords.Add("nay: no");
	gacArchaicWords.Add("neat: a bovine animal or animals");
	gacArchaicWords.Add("nice: fastidious");
	gacArchaicWords.Add("nigh: near");
	gacArchaicWords.Add("nithing: a contemptible or despicable person");
	gacArchaicWords.Add("noise(something) about: talk about or make known publicly");
	gacArchaicWords.Add("nubbing - cheat: a gallows");
	gacArchaicWords.Add("numbles: a deer's entrails as food");
	gacArchaicWords.Add("orison: a prayer");
	gacArchaicWords.Add("orts: scraps; remains");
	gacArchaicWords.Add("otherwhere: elsewhere");
	gacArchaicWords.Add("otiose: lazy; slothful");
	gacArchaicWords.Add("overbrim: spill; overflow");
	gacArchaicWords.Add("overleap: jump over or across");
	gacArchaicWords.Add("overset: capsize; flip over");
	gacArchaicWords.Add("pale: an area within determined bounds or subject to a particular jurisdiction");
	gacArchaicWords.Add("palfrey: a docile riding horse");
	gacArchaicWords.Add("pate: a person's head");
	gacArchaicWords.Add("paynim: a pagan");
	gacArchaicWords.Add("peccant: sinful; offending");
	gacArchaicWords.Add("peeler: a police officer");
	gacArchaicWords.Add("pelf: money, especially when gained dishonestly");
	gacArchaicWords.Add("peradventure: perhaps");
	gacArchaicWords.Add("perchance: by some chance");
	gacArchaicWords.Add("peregrinate: travel or wander from place to place");
	gacArchaicWords.Add("periapt: a charm or amulet");
	gacArchaicWords.Add("pest: bubonic plague");
	gacArchaicWords.Add("pestilence: a fatal epidemic disease, especially bubonic plague");
	gacArchaicWords.Add("peterman: a thief or safecracker");
	gacArchaicWords.Add("physic: medicinal drugs or medical treatment");
	gacArchaicWords.Add("picaroon: a scoundrel");
	gacArchaicWords.Add("piepowder: a traveller or an itinerant merchant or trader");
	gacArchaicWords.Add("pismire: an ant");
	gacArchaicWords.Add("pistoleer: a soldier armed with a pistol");
	gacArchaicWords.Add("plain over: lament; cry over");
	gacArchaicWords.Add("plight: solemnly pledge or promise(faith or loyalty)");
	gacArchaicWords.Add("pollard: an animal that has lost its horns or cast its antlers");
	gacArchaicWords.Add("poltroon: an utter coward");
	gacArchaicWords.Add("popinjay: a parrot");
	gacArchaicWords.Add("pore on: think about");
	gacArchaicWords.Add("portage: the action of carrying or transporting");
	gacArchaicWords.Add("portion: a dowry");
	gacArchaicWords.Add("portion: a person's destiny or lot");
	gacArchaicWords.Add("posy: a short motto or line of verse inscribed inside a ring");
	gacArchaicWords.Add("potation: a beverage");
	gacArchaicWords.Add("pouncet - box: a small box with a perforated lid used for holding a substance impregnated with perfume");
	gacArchaicWords.Add("prithee: please");
	gacArchaicWords.Add("profess: teach(a subject) as a professor");
	gacArchaicWords.Add("purblind: short - sighted");
	gacArchaicWords.Add("purfle: an ornamental or embroidered edge of a garment");
	gacArchaicWords.Add("pythoness: a woman believed to be possessed by a spirit and to be able to foresee the future");
	gacArchaicWords.Add("quaggy: marshy or boggy");
	gacArchaicWords.Add("quality: high social standing");
	gacArchaicWords.Add("quean: an impudent girl or woman");
	gacArchaicWords.Add("quick, the: the living");
	gacArchaicWords.Add("quidnunc: an inquisitive, gossipy person");
	gacArchaicWords.Add("quiz: look intently at(someone)");
	gacArchaicWords.Add("quoth: said(in I / he / she quoth)");
	gacArchaicWords.Add("rack(of a cloud) be driven by the wind");
	gacArchaicWords.Add("raiment: clothing");
	gacArchaicWords.Add("rapscallion: a mischievous person");
	gacArchaicWords.Add("rathe - ripe(of fruit) ripening early in the year; (of a person) precocious");
	gacArchaicWords.Add("reave: carry out a plundering raid");
	gacArchaicWords.Add("receipt: a recipe");
	gacArchaicWords.Add("recipe: a medical prescription");
	gacArchaicWords.Add("recompense: punish or reward appropriately");
	gacArchaicWords.Add("recreant: cowardly");
	gacArchaicWords.Add("rede: advice or counsel");
	gacArchaicWords.Add("reduce: besiege and capture(a town or fortress)");
	gacArchaicWords.Add("relieve: make(something) stand out");
	gacArchaicWords.Add("remit: diminish");
	gacArchaicWords.Add("repair: an abode or haunt");
	gacArchaicWords.Add("repulsive: lacking friendliness or sympathy");
	gacArchaicWords.Add("riband: a ribbon");
	gacArchaicWords.Add("rover: a pirate");
	gacArchaicWords.Add("rude: ignorant and uneducated");
	gacArchaicWords.Add("ruth: a feeling of pity, distress, or grief");
	gacArchaicWords.Add("sables: black mourning clothes");
	gacArchaicWords.Add("sacring: the consecration of a bishop, a sovereign, or the Eucharistic elements");
	gacArchaicWords.Add("saddle - bow: the pommel of a saddle");
	gacArchaicWords.Add("salamander: a red - hot iron or poker");
	gacArchaicWords.Add("sanative: healing");
	gacArchaicWords.Add("sanguinary: involving or causing much bloodshed");
	gacArchaicWords.Add("sap: make(a building, etc.) insecure by removing its foundations");
	gacArchaicWords.Add("saturnism: lead poisoning");
	gacArchaicWords.Add("scantling: a specimen, sample, or small amount");
	gacArchaicWords.Add("scapegrace: a mischievous person; a rascal");
	gacArchaicWords.Add("scaramouch: a boastful but cowardly person");
	gacArchaicWords.Add("schoolman: a teacher");
	gacArchaicWords.Add("science: knowledge");
	gacArchaicWords.Add("sciolist: a person who pretends to be knowledgeable");
	gacArchaicWords.Add("scold: a woman who nags or grumbles constantly");
	gacArchaicWords.Add("scot: a tax - like payment");
	gacArchaicWords.Add("scrag: a neck");
	gacArchaicWords.Add("scruple: a very small amount of something, especially a quality");
	gacArchaicWords.Add("scullion: a menial servant");
	gacArchaicWords.Add("scurvy: worthless or contemptible");
	gacArchaicWords.Add("sea coal: mineral coal");
	gacArchaicWords.Add("sea smoke: fog");
	gacArchaicWords.Add("seizing: a length of cord or rope on board a ship");
	gacArchaicWords.Add("sennight: a week");
	gacArchaicWords.Add("sepulture: burial");
	gacArchaicWords.Add("shambles: a slaughterhouse");
	gacArchaicWords.Add("shrift: forgiveness");
	gacArchaicWords.Add("shrive(of a priest) absolve(a person making a confession)");
	gacArchaicWords.Add("silly: helpless; defenceless");
	gacArchaicWords.Add("sippet: a small piece of bread or toast for dipping into soup or sauce");
	gacArchaicWords.Add("skirt: an edge, border, or extreme part");
	gacArchaicWords.Add("slay: kill in a violent way");
	gacArchaicWords.Add("slipshod(of shoes) worn down at the heel");
	gacArchaicWords.Add("slugabed: a lazy person who stays in bed late");
	gacArchaicWords.Add("small beer: weak beer");
	gacArchaicWords.Add("smite: defeat or conquer");
	gacArchaicWords.Add("soak: drink heavily");
	gacArchaicWords.Add("soft tack: bread, especially as rations for sailors or soldiers");
	gacArchaicWords.Add("soil: a stain");
	gacArchaicWords.Add("sooth: truth");
	gacArchaicWords.Add("sore: extremely; severely");
	gacArchaicWords.Add("speed: success; prosperity");
	gacArchaicWords.Add("spence: a pantry or larder");
	gacArchaicWords.Add("statuary: a sculptor");
	gacArchaicWords.Add("steed: a horse");
	gacArchaicWords.Add("stoup: a container for drinking beer, etc.; a flagon");
	gacArchaicWords.Add("stripe: a blow with a lash");
	gacArchaicWords.Add("strumpet: a female prostitute or a promiscuous woman");
	gacArchaicWords.Add("success: a good or bad outcome");
	gacArchaicWords.Add("suffer: endure; tolerate");
	gacArchaicWords.Add("surety, of / for a: for certain");
	gacArchaicWords.Add("swain: a country youth");
	gacArchaicWords.Add("swash: flamboyantly swagger about or wield a sword");
	gacArchaicWords.Add("sweeting: darling");
	gacArchaicWords.Add("sweetmeat: an item of confectionery or sweet food");
	gacArchaicWords.Add("taiga: a forest");
	gacArchaicWords.Add("tantivy: a rapid gallop or ride");
	gacArchaicWords.Add("tapster: a person who serves at a bar");
	gacArchaicWords.Add("tenter: a person in charge of something, especially factory machinery");
	gacArchaicWords.Add("thenceforth: from that time, place, or point onward");
	gacArchaicWords.Add("thereunto: to that");
	gacArchaicWords.Add("therewith: with or in the thing mentioned");
	gacArchaicWords.Add("thither: to or toward that place");
	gacArchaicWords.Add("thrice: three times");
	gacArchaicWords.Add("tilt with: engage in a contest with");
	gacArchaicWords.Add("timbrel: a tambourine or similar instrument");
	gacArchaicWords.Add("tithe: a tenth");
	gacArchaicWords.Add("tocsin: an alarm bell or signal");
	gacArchaicWords.Add("tope: drink to excess");
	gacArchaicWords.Add("trespass: a sin or offence");
	gacArchaicWords.Add("trig: neat and smart");
	gacArchaicWords.Add("trigon: a triangle");
	gacArchaicWords.Add("troth: faith or loyalty when pledged in a solemn undertaking");
	gacArchaicWords.Add("truck: an exchange or transaction");
	gacArchaicWords.Add("turnkey: a jailer");
	gacArchaicWords.Add("tweeny: a maid who assisted both the cook and the housemaid");
	gacArchaicWords.Add("twelvemonth: a year");
	gacArchaicWords.Add("uncle: a pawnbroker");
	gacArchaicWords.Add("uncommon: remarkably");
	gacArchaicWords.Add("up to snuff: up to the required standard");
	gacArchaicWords.Add("usher: an assistant teacher");
	gacArchaicWords.Add("vale: a farewell; a send - off");
	gacArchaicWords.Add("varlet: an unprincipled rogue");
	gacArchaicWords.Add("venery: hunting");
	gacArchaicWords.Add("verily: truly; certainly");
	gacArchaicWords.Add("verse: a line of poetry");
	gacArchaicWords.Add("very: real; genuine");
	gacArchaicWords.Add("virtue: virginity");
	gacArchaicWords.Add("visionary: existing only in the imagination");
	gacArchaicWords.Add("wain: a wagon or cart");
	gacArchaicWords.Add("wait on / upon: pay a respectful visit to");
	gacArchaicWords.Add("waits: street singers of Christmas carols");
	gacArchaicWords.Add("ware of: aware of");
	gacArchaicWords.Add("wassail: revelry");
	gacArchaicWords.Add("wast: second person singular past of be");
	gacArchaicWords.Add("watch: remain awake as religious observance");
	gacArchaicWords.Add("watchful: wakeful");
	gacArchaicWords.Add("watchword: a military password");
	gacArchaicWords.Add("weasand: the oesophagus or gullet");
	gacArchaicWords.Add("ween: think or suppose; be of the opinion");
	gacArchaicWords.Add("wench: a girl or young woman");
	gacArchaicWords.Add("whence: from what place or source");
	gacArchaicWords.Add("whereat: at which");
	gacArchaicWords.Add("wherefore: for what reason");
	gacArchaicWords.Add("wherewith: with or by which");
	gacArchaicWords.Add("whilom: formerly");
	gacArchaicWords.Add("white goods: domestic linen");
	gacArchaicWords.Add("whither: to what place or state");
	gacArchaicWords.Add("wife: a woman, especially an old or uneducated one");
	gacArchaicWords.Add("wight: a person of a specified kind");
	gacArchaicWords.Add("wise: manner, way, or extent");
	gacArchaicWords.Add("withal: in addition");
	gacArchaicWords.Add("without: outside");
	gacArchaicWords.Add("wondrous: wonderfully");
	gacArchaicWords.Add("wont: accustomed");
	gacArchaicWords.Add("wonted: usual");
	gacArchaicWords.Add("wool - stapler: a dealer in wool");
	gacArchaicWords.Add("wright: a maker or builder");
	gacArchaicWords.Add("yclept: by the name of");
	gacArchaicWords.Add("ye: you");
	gacArchaicWords.Add("yea: yes");
	gacArchaicWords.Add("yoke: the amount of land that one pair of oxen could plough in a day");
	gacArchaicWords.Add("yonder: over there");
	gacArchaicWords.Add("zounds: an expression of surprise or indignation");
}


//////////////////////////////////////////////////////////////////////////
//
//
//////////////////////////////////////////////////////////////////////////
void WordsKill(void)
{
	gacArchaicWords.Kill();
}

