#include "Words.h"


CArrayChars gaszArchaicWords;
CArrayChars gaszArchaicDefinitions;
CArrayChars gaszCommonWords;


//////////////////////////////////////////////////////////////////////////
//
//
//////////////////////////////////////////////////////////////////////////
void GetArchaicDefinitions(CArrayChars* pasz)
{
	pasz->Add("abroad: out of doors");
	pasz->Add("accouchement: birthing");
	pasz->Add("advertisement: a notice to readers in a book");
	pasz->Add("afeard / afeared: frightened");
	pasz->Add("affright: frighten(someone)");
	pasz->Add("ague: malaria or a similar illness");
	pasz->Add("aliment: food; nourishment");
	pasz->Add("ambuscade: an ambush");
	pasz->Add("animalcule: a microscopic animal");
	pasz->Add("apothecary: a person who prepared and sold medicine");
	pasz->Add("appetency: a longing or desire");
	pasz->Add("assay: attempt");
	pasz->Add("asunder: apart");
	pasz->Add("audition: the power of hearing");
	pasz->Add("aught: anything at all");
	pasz->Add("avaunt: go away");
	pasz->Add("bane: poison");
	pasz->Add("baseborn: of low birth or social standing");
	pasz->Add("bedlam: an asylum");
	pasz->Add("behold: see or observe");
	pasz->Add("behoof: benefit or advantage");
	pasz->Add("beldam: an old woman");
	pasz->Add("bethink oneself of: remember; recollect");
	pasz->Add("betimes: in good time; early");
	pasz->Add("bibliopole: a dealer in books");
	pasz->Add("bijoux: jewellery; trinkets");
	pasz->Add("billow: a large sea wave");
	pasz->Add("blackguard: a scoundrel");
	pasz->Add("blow: produce flowers or be in flower");
	pasz->Add("bodkin: a dagger");
	pasz->Add("bootless(of a task) ineffectual; useless");
	pasz->Add("breech: a person's buttocks");
	pasz->Add("bridewell: a prison or reform school for petty offenders");
	pasz->Add("brimstone: sulphur");
	pasz->Add("bruit: a report or rumour");
	pasz->Add("buck: a fashionable and daring young man");
	pasz->Add("bumper: a generous glass of an alcoholic drink");
	pasz->Add("burgess: a full citizen of a town or borough");
	pasz->Add("buss: a kiss");
	pasz->Add("caboose: a kitchen on a ship's deck");
	pasz->Add("cadet: a younger son or daughter");
	pasz->Add("caducity: the infirmity of old age; senility");
	pasz->Add("camelopard: a giraffe");
	pasz->Add("cannonade: bombard");
	pasz->Add("carl: a man of low birth");
	pasz->Add("ceil: line or plaster the roof of(a building)");
	pasz->Add("champaign: open level countryside");
	pasz->Add("chapman: a peddler");
	pasz->Add("chicane: deceive; hoodwink");
	pasz->Add("circumjacent: surrounding");
	pasz->Add("cicisbeo: a married woman's male companion or lover");
	pasz->Add("cispontine: on the north side of the Thames in London");
	pasz->Add("cleanse: restore to health");
	pasz->Add("clerk: a literate or scholarly person");
	pasz->Add("clew: a ball of thread");
	pasz->Add("clout: a piece of cloth or clothing");
	pasz->Add("collogue: talk confidentially");
	pasz->Add("commend: entrust someone or something to");
	pasz->Add("commons: provisions shared in common; rations");
	pasz->Add("communicant: a person who imparts information");
	pasz->Add("compass: encircle or surround");
	pasz->Add("compeer: a companion or close associate");
	pasz->Add("con: study attentively or learn by heart(a piece of writing)");
	pasz->Add("condition: social position");
	pasz->Add("conjure: implore(someone) to do something");
	pasz->Add("contemn: treat or regard with contempt");
	pasz->Add("contumely: insolent or insulting language or treatment");
	pasz->Add("cordwainer: a shoemaker");
	pasz->Add("corrupt: rotten or putrid");
	pasz->Add("corse: a corpse");
	pasz->Add("cottier: a rural labourer living in a cottage");
	pasz->Add("coxcomb: a vain and conceited man; a dandy");
	pasz->Add("coz: cousin");
	pasz->Add("crinkum - crankum: elaborate decoration or detail");
	pasz->Add("crookback: a person with a hunchback");
	pasz->Add("crumpet: a person's head");
	pasz->Add("cruse: an earthenware pot or jar");
	pasz->Add("cully: a friendly form of address for a man");
	pasz->Add("cutpurse: a pickpocket");
	pasz->Add("dame: an elderly or mature woman");
	pasz->Add("damsel: a young unmarried woman");
	pasz->Add("dandiprat: a young or insignificant person");
	pasz->Add("darbies: handcuffs");
	pasz->Add("dark: ignorant");
	pasz->Add("degrade: reduce to a lower rank, especially as a punishment");
	pasz->Add("degree: social or official rank");
	pasz->Add("delate: report(an offence)");
	pasz->Add("demesne: a region or domain");
	pasz->Add("demit: resign from(an office or position)");
	pasz->Add("demoralize: corrupt the morals of");
	pasz->Add("dight: clothed or equipped");
	pasz->Add("discover: divulge(a secret)");
	pasz->Add("disport: frolic");
	pasz->Add("dispraise: censure or criticize");
	pasz->Add("divers: of varying types; several");
	pasz->Add("doit: a very small amount of money");
	pasz->Add("dot: a dowry from which only the interest or annual income was available to the husband");
	pasz->Add("doxy: a lover or mistress");
	pasz->Add("drab: a slovenly woman");
	pasz->Add("drought: thirst");
	pasz->Add("egad: exclamation of surprise, anger, or affirmation");
	pasz->Add("embarrass: hamper or impede");
	pasz->Add("embouchure: the mouth of a river");
	pasz->Add("equipage: gear; equipment");
	pasz->Add("ere: before(in time)");
	pasz->Add("espousal: a marriage or engagement");
	pasz->Add("estate: a particular state, period, or condition in life");
	pasz->Add("esurient: hungry");
	pasz->Add("expectations: one's prospects of inheritance");
	pasz->Add("expiry: death");
	pasz->Add("fain: pleased or willing under the circumstances");
	pasz->Add("fainéant: an idle or ineffective person");
	pasz->Add("fair: beautiful");
	pasz->Add("fandangle: a useless or purely ornamental thing");
	pasz->Add("fane: a shrine or temple");
	pasz->Add("fare: travel");
	pasz->Add("fell: an animal skin; a pelt");
	pasz->Add("feminal: feminine; womanly");
	pasz->Add("fervent: hot or glowing");
	pasz->Add("fie: exclamation used to express disgust or outrage");
	pasz->Add("filibeg: a kilt");
	pasz->Add("fishwife: a woman who sells fish");
	pasz->Add("fizgig: a silly or flirtatious young woman");
	pasz->Add("flux: diarrhoea or dysentery");
	pasz->Add("forfend: avert or prevent(something evil or unpleasant)");
	pasz->Add("forsooth: indeed");
	pasz->Add("fourscore: eighty");
	pasz->Add("freak: a whim");
	pasz->Add("frore: frozen or frosty");
	pasz->Add("froward(of a person) difficult to deal with; contrary");
	pasz->Add("fruit: offspring");
	pasz->Add("fudge: nonsense");
	pasz->Add("furbish: polish(a weapon)");
	pasz->Add("gadzooks: an expression of surprise or annoyance");
	pasz->Add("gage: a valued object deposited as a guarantee");
	pasz->Add("gallant: a dashing gentleman");
	pasz->Add("gammer: an old woman");
	pasz->Add("garland: a literary anthology");
	pasz->Add("garth: a yard or garden");
	pasz->Add("gaud: a trinket");
	pasz->Add("gentle: noble or courteous");
	pasz->Add("glabriety: baldness");
	pasz->Add("glaciate: freeze over");
	pasz->Add("glebe: a meadow");
	pasz->Add("glim: a candle");
	pasz->Add("go - cart: a baby walker");
	pasz->Add("God's acre: a churchyard");
	pasz->Add("goodly: attractive, excellent, or virtuous");
	pasz->Add("goody(with a name) an elderly woman of humble position");
	pasz->Add("grateful: received with gratitude");
	pasz->Add("greenwood: a forest");
	pasz->Add("grimalkin: a cat");
	pasz->Add("gudgeon: a credulous person");
	pasz->Add("guerdon: a reward");
	pasz->Add("gyve: a fetter or shackle");
	pasz->Add("habiliment: clothing");
	pasz->Add("halt: lame");
	pasz->Add("handmaid: a female servant");
	pasz->Add("hearken: listen");
	pasz->Add("hence: from here");
	pasz->Add("herbary: a herb garden");
	pasz->Add("hereat: as a result of this");
	pasz->Add("hereunto: to this document");
	pasz->Add("hereupon: after or as a result of this");
	pasz->Add("hie: go quickly");
	pasz->Add("hight: named");
	pasz->Add("hither: to or toward this place");
	pasz->Add("hoar: frost");
	pasz->Add("horse - coper: a person who deals in horses");
	pasz->Add("horseless carriage: a car");
	pasz->Add("host: an army");
	pasz->Add("howbeit: nevertheless");
	pasz->Add("husbandman: a farmer");
	pasz->Add("immedicable: untreatable");
	pasz->Add("imminent: overhanging");
	pasz->Add("indite: write; compose");
	pasz->Add("inscribe: enter the name of(someone) on a list");
	pasz->Add("in sooth: actually");
	pasz->Add("intelligence: news");
	pasz->Add("intelligencer: a person who gathers intelligence");
	pasz->Add("invest: surround(a place) in order to besiege or blockade it");
	pasz->Add("iron horse: a steam locomotive");
	pasz->Add("izzard: the letter Z");
	pasz->Add("jade: a bad - tempered or disreputable woman");
	pasz->Add("jakes: an outdoor toilet");
	pasz->Add("job: turn a public office or a position of trust to private advantage");
	pasz->Add("kickshaw: a fancy but insubstantial cooked dish");
	pasz->Add("kine: cows collectively");
	pasz->Add("kirtle: a woman's gown or a man's tunic");
	pasz->Add("knave: a dishonest or unscrupulous man");
	pasz->Add("larcener: thief");
	pasz->Add("latchet: a narrow thong or lace for fastening a shoe or sandal");
	pasz->Add("laud: praise");
	pasz->Add("laver: a basin or similar container used for washing oneself");
	pasz->Add("learn: teach");
	pasz->Add("leech: a doctor or healer");
	pasz->Add("leman: a lover or sweetheart");
	pasz->Add("let: hinder");
	pasz->Add("levant: abscond leaving unpaid debts");
	pasz->Add("Levant: the eastern part of the Mediterranean");
	pasz->Add("levy: a body of enlisted troops");
	pasz->Add("lief: as happily; as gladly");
	pasz->Add("like enough: probably");
	pasz->Add("loathly: repulsive");
	pasz->Add("lordling: a minor lord");
	pasz->Add("love apple: a tomato");
	pasz->Add("Lucifer: a match");
	pasz->Add("lurdan: an idle or incompetent person");
	pasz->Add("lying - in: seclusion before and after childbirth");
	pasz->Add("magdalen: a reformed prostitute");
	pasz->Add("mage: a magician or learned person");
	pasz->Add("magnify: glorify; extol");
	pasz->Add("maid: a girl or young woman");
	pasz->Add("malapert: presumptuous and impudent");
	pasz->Add("malison: a curse");
	pasz->Add("man - at - arms: a soldier");
	pasz->Add("marry: an expression of surprise, indignation, or emphatic assertion");
	pasz->Add("mayhap: perhaps; possibly");
	pasz->Add("mazed: bewildered");
	pasz->Add("measure: a dance");
	pasz->Add("meat: food of any kind");
	pasz->Add("mechanical: a manual worker");
	pasz->Add("meet: suitable or proper");
	pasz->Add("melodist: a singer");
	pasz->Add("methinks: it seems to me");
	pasz->Add("moil: drudgery");
	pasz->Add("mooncalf: a foolish person");
	pasz->Add("morrow, the: the following day");
	pasz->Add("mummer: an actor in the theatre");
	pasz->Add("natheless: nevertheless");
	pasz->Add("natural: a person born with impaired intelligence");
	pasz->Add("naught: nothing");
	pasz->Add("nay: no");
	pasz->Add("neat: a bovine animal or animals");
	pasz->Add("nice: fastidious");
	pasz->Add("nigh: near");
	pasz->Add("nithing: a contemptible or despicable person");
	pasz->Add("noise(something) about: talk about or make known publicly");
	pasz->Add("nubbing - cheat: a gallows");
	pasz->Add("numbles: a deer's entrails as food");
	pasz->Add("orison: a prayer");
	pasz->Add("orts: scraps; remains");
	pasz->Add("otherwhere: elsewhere");
	pasz->Add("otiose: lazy; slothful");
	pasz->Add("overbrim: spill; overflow");
	pasz->Add("overleap: jump over or across");
	pasz->Add("overset: capsize; flip over");
	pasz->Add("pale: an area within determined bounds or subject to a particular jurisdiction");
	pasz->Add("palfrey: a docile riding horse");
	pasz->Add("pate: a person's head");
	pasz->Add("paynim: a pagan");
	pasz->Add("peccant: sinful; offending");
	pasz->Add("peeler: a police officer");
	pasz->Add("pelf: money, especially when gained dishonestly");
	pasz->Add("peradventure: perhaps");
	pasz->Add("perchance: by some chance");
	pasz->Add("peregrinate: travel or wander from place to place");
	pasz->Add("periapt: a charm or amulet");
	pasz->Add("pest: bubonic plague");
	pasz->Add("pestilence: a fatal epidemic disease, especially bubonic plague");
	pasz->Add("peterman: a thief or safecracker");
	pasz->Add("physic: medicinal drugs or medical treatment");
	pasz->Add("picaroon: a scoundrel");
	pasz->Add("piepowder: a traveller or an itinerant merchant or trader");
	pasz->Add("pismire: an ant");
	pasz->Add("pistoleer: a soldier armed with a pistol");
	pasz->Add("plain over: lament; cry over");
	pasz->Add("plight: solemnly pledge or promise(faith or loyalty)");
	pasz->Add("pollard: an animal that has lost its horns or cast its antlers");
	pasz->Add("poltroon: an utter coward");
	pasz->Add("popinjay: a parrot");
	pasz->Add("pore on: think about");
	pasz->Add("portage: the action of carrying or transporting");
	pasz->Add("portion: a dowry");
	pasz->Add("portion: a person's destiny or lot");
	pasz->Add("posy: a short motto or line of verse inscribed inside a ring");
	pasz->Add("potation: a beverage");
	pasz->Add("pouncet - box: a small box with a perforated lid used for holding a substance impregnated with perfume");
	pasz->Add("prithee: please");
	pasz->Add("profess: teach(a subject) as a professor");
	pasz->Add("purblind: short - sighted");
	pasz->Add("purfle: an ornamental or embroidered edge of a garment");
	pasz->Add("pythoness: a woman believed to be possessed by a spirit and to be able to foresee the future");
	pasz->Add("quaggy: marshy or boggy");
	pasz->Add("quality: high social standing");
	pasz->Add("quean: an impudent girl or woman");
	pasz->Add("quick, the: the living");
	pasz->Add("quidnunc: an inquisitive, gossipy person");
	pasz->Add("quiz: look intently at(someone)");
	pasz->Add("quoth: said(in I / he / she quoth)");
	pasz->Add("rack(of a cloud) be driven by the wind");
	pasz->Add("raiment: clothing");
	pasz->Add("rapscallion: a mischievous person");
	pasz->Add("rathe - ripe(of fruit) ripening early in the year; (of a person) precocious");
	pasz->Add("reave: carry out a plundering raid");
	pasz->Add("receipt: a recipe");
	pasz->Add("recipe: a medical prescription");
	pasz->Add("recompense: punish or reward appropriately");
	pasz->Add("recreant: cowardly");
	pasz->Add("rede: advice or counsel");
	pasz->Add("reduce: besiege and capture(a town or fortress)");
	pasz->Add("relieve: make(something) stand out");
	pasz->Add("remit: diminish");
	pasz->Add("repair: an abode or haunt");
	pasz->Add("repulsive: lacking friendliness or sympathy");
	pasz->Add("riband: a ribbon");
	pasz->Add("rover: a pirate");
	pasz->Add("rude: ignorant and uneducated");
	pasz->Add("ruth: a feeling of pity, distress, or grief");
	pasz->Add("sables: black mourning clothes");
	pasz->Add("sacring: the consecration of a bishop, a sovereign, or the Eucharistic elements");
	pasz->Add("saddle - bow: the pommel of a saddle");
	pasz->Add("salamander: a red - hot iron or poker");
	pasz->Add("sanative: healing");
	pasz->Add("sanguinary: involving or causing much bloodshed");
	pasz->Add("sap: make(a building, etc.) insecure by removing its foundations");
	pasz->Add("saturnism: lead poisoning");
	pasz->Add("scantling: a specimen, sample, or small amount");
	pasz->Add("scapegrace: a mischievous person; a rascal");
	pasz->Add("scaramouch: a boastful but cowardly person");
	pasz->Add("schoolman: a teacher");
	pasz->Add("science: knowledge");
	pasz->Add("sciolist: a person who pretends to be knowledgeable");
	pasz->Add("scold: a woman who nags or grumbles constantly");
	pasz->Add("scot: a tax - like payment");
	pasz->Add("scrag: a neck");
	pasz->Add("scruple: a very small amount of something, especially a quality");
	pasz->Add("scullion: a menial servant");
	pasz->Add("scurvy: worthless or contemptible");
	pasz->Add("sea coal: mineral coal");
	pasz->Add("sea smoke: fog");
	pasz->Add("seizing: a length of cord or rope on board a ship");
	pasz->Add("sennight: a week");
	pasz->Add("sepulture: burial");
	pasz->Add("shambles: a slaughterhouse");
	pasz->Add("shrift: forgiveness");
	pasz->Add("shrive(of a priest) absolve(a person making a confession)");
	pasz->Add("silly: helpless; defenceless");
	pasz->Add("sippet: a small piece of bread or toast for dipping into soup or sauce");
	pasz->Add("skirt: an edge, border, or extreme part");
	pasz->Add("slay: kill in a violent way");
	pasz->Add("slipshod(of shoes) worn down at the heel");
	pasz->Add("slugabed: a lazy person who stays in bed late");
	pasz->Add("small beer: weak beer");
	pasz->Add("smite: defeat or conquer");
	pasz->Add("soak: drink heavily");
	pasz->Add("soft tack: bread, especially as rations for sailors or soldiers");
	pasz->Add("soil: a stain");
	pasz->Add("sooth: truth");
	pasz->Add("sore: extremely; severely");
	pasz->Add("speed: success; prosperity");
	pasz->Add("spence: a pantry or larder");
	pasz->Add("statuary: a sculptor");
	pasz->Add("steed: a horse");
	pasz->Add("stoup: a container for drinking beer, etc.; a flagon");
	pasz->Add("stripe: a blow with a lash");
	pasz->Add("strumpet: a female prostitute or a promiscuous woman");
	pasz->Add("success: a good or bad outcome");
	pasz->Add("suffer: endure; tolerate");
	pasz->Add("surety, of / for a: for certain");
	pasz->Add("swain: a country youth");
	pasz->Add("swash: flamboyantly swagger about or wield a sword");
	pasz->Add("sweeting: darling");
	pasz->Add("sweetmeat: an item of confectionery or sweet food");
	pasz->Add("taiga: a forest");
	pasz->Add("tantivy: a rapid gallop or ride");
	pasz->Add("tapster: a person who serves at a bar");
	pasz->Add("tenter: a person in charge of something, especially factory machinery");
	pasz->Add("thenceforth: from that time, place, or point onward");
	pasz->Add("thereunto: to that");
	pasz->Add("therewith: with or in the thing mentioned");
	pasz->Add("thither: to or toward that place");
	pasz->Add("thrice: three times");
	pasz->Add("tilt with: engage in a contest with");
	pasz->Add("timbrel: a tambourine or similar instrument");
	pasz->Add("tithe: a tenth");
	pasz->Add("tocsin: an alarm bell or signal");
	pasz->Add("tope: drink to excess");
	pasz->Add("trespass: a sin or offence");
	pasz->Add("trig: neat and smart");
	pasz->Add("trigon: a triangle");
	pasz->Add("troth: faith or loyalty when pledged in a solemn undertaking");
	pasz->Add("truck: an exchange or transaction");
	pasz->Add("turnkey: a jailer");
	pasz->Add("tweeny: a maid who assisted both the cook and the housemaid");
	pasz->Add("twelvemonth: a year");
	pasz->Add("uncle: a pawnbroker");
	pasz->Add("uncommon: remarkably");
	pasz->Add("up to snuff: up to the required standard");
	pasz->Add("usher: an assistant teacher");
	pasz->Add("vale: a farewell; a send - off");
	pasz->Add("varlet: an unprincipled rogue");
	pasz->Add("venery: hunting");
	pasz->Add("verily: truly; certainly");
	pasz->Add("verse: a line of poetry");
	pasz->Add("very: real; genuine");
	pasz->Add("virtue: virginity");
	pasz->Add("visionary: existing only in the imagination");
	pasz->Add("wain: a wagon or cart");
	pasz->Add("wait on / upon: pay a respectful visit to");
	pasz->Add("waits: street singers of Christmas carols");
	pasz->Add("ware of: aware of");
	pasz->Add("wassail: revelry");
	pasz->Add("wast: second person singular past of be");
	pasz->Add("watch: remain awake as religious observance");
	pasz->Add("watchful: wakeful");
	pasz->Add("watchword: a military password");
	pasz->Add("weasand: the oesophagus or gullet");
	pasz->Add("ween: think or suppose; be of the opinion");
	pasz->Add("wench: a girl or young woman");
	pasz->Add("whence: from what place or source");
	pasz->Add("whereat: at which");
	pasz->Add("wherefore: for what reason");
	pasz->Add("wherewith: with or by which");
	pasz->Add("whilom: formerly");
	pasz->Add("white goods: domestic linen");
	pasz->Add("whither: to what place or state");
	pasz->Add("wife: a woman, especially an old or uneducated one");
	pasz->Add("wight: a person of a specified kind");
	pasz->Add("wise: manner, way, or extent");
	pasz->Add("withal: in addition");
	pasz->Add("without: outside");
	pasz->Add("wondrous: wonderfully");
	pasz->Add("wont: accustomed");
	pasz->Add("wonted: usual");
	pasz->Add("wool - stapler: a dealer in wool");
	pasz->Add("wright: a maker or builder");
	pasz->Add("yclept: by the name of");
	pasz->Add("ye: you");
	pasz->Add("yea: yes");
	pasz->Add("yoke: the amount of land that one pair of oxen could plough in a day");
	pasz->Add("yonder: over there");
	pasz->Add("zounds: an expression of surprise or indignation");
}


//////////////////////////////////////////////////////////////////////////
//
//
//////////////////////////////////////////////////////////////////////////
void GetArchaicWords(CArrayChars* pasz)
{
	int		i;
	CChars* pszDefinition;
	int		iIndex;
	CChars	sz;

	for (i = 0; i < gaszArchaicDefinitions.NumElements(); i++)
	{
		pszDefinition = gaszArchaicDefinitions.Get(i);
		iIndex = pszDefinition->Find(':');
		if (iIndex != -1)
		{
			sz.Init(pszDefinition->Text(), 0, iIndex - 1);
			gaszArchaicWords.Add(sz);
			sz.Kill();
		}
		else
		{
			gaszArchaicWords.Add(pszDefinition->Text());
		}
	}
}


//////////////////////////////////////////////////////////////////////////
//
//
//////////////////////////////////////////////////////////////////////////
void GetCommonWords(CArrayChars* pasz)
{
	pasz->Add("a");;
	pasz->Add("ability");
	pasz->Add("able");
	pasz->Add("about");
	pasz->Add("above");
	pasz->Add("accept");
	pasz->Add("according");
	pasz->Add("account");
	pasz->Add("acrossn");
	pasz->Add("actn");
	pasz->Add("actionn");
	pasz->Add("activityn");
	pasz->Add("actuallyn");
	pasz->Add("addn");
	pasz->Add("addressn");
	pasz->Add("administrationn");
	pasz->Add("admitn");
	pasz->Add("adultn");
	pasz->Add("affectn");
	pasz->Add("aftern");
	pasz->Add("againn");
	pasz->Add("againstn");
	pasz->Add("agen");
	pasz->Add("agencyn");
	pasz->Add("agentn");
	pasz->Add("agon");
	pasz->Add("agreen");
	pasz->Add("agreementn");
	pasz->Add("aheadn");
	pasz->Add("airn");
	pasz->Add("alln");
	pasz->Add("allown");
	pasz->Add("almostn");
	pasz->Add("alonen");
	pasz->Add("alongn");
	pasz->Add("alreadyn");
	pasz->Add("alson");
	pasz->Add("althoughn");
	pasz->Add("alwaysn");
	pasz->Add("Americann");
	pasz->Add("amongn");
	pasz->Add("amountn");
	pasz->Add("analysisn");
	pasz->Add("andn");
	pasz->Add("animaln");
	pasz->Add("anothern");
	pasz->Add("answern");
	pasz->Add("anyn");
	pasz->Add("anyonen");
	pasz->Add("anythingn");
	pasz->Add("appearn");
	pasz->Add("applyn");
	pasz->Add("approachn");
	pasz->Add("arean");
	pasz->Add("arguen");
	pasz->Add("armn");
	pasz->Add("aroundn");
	pasz->Add("arriven");
	pasz->Add("artn");
	pasz->Add("articlen");
	pasz->Add("artistn");
	pasz->Add("asn");
	pasz->Add("askn");
	pasz->Add("assumen");
	pasz->Add("atn");
	pasz->Add("attackn");
	pasz->Add("attentionn");
	pasz->Add("attorneyn");
	pasz->Add("audiencen");
	pasz->Add("authorn");
	pasz->Add("authorityn");
	pasz->Add("availablen");
	pasz->Add("avoidn");
	pasz->Add("awayn");
	pasz->Add("babyn");
	pasz->Add("backn");
	pasz->Add("badn");
	pasz->Add("bagn");
	pasz->Add("balln");
	pasz->Add("bankn");
	pasz->Add("barn");
	pasz->Add("basen");
	pasz->Add("ben");
	pasz->Add("beatn");
	pasz->Add("beautifuln");
	pasz->Add("becausen");
	pasz->Add("becomen");
	pasz->Add("bedn");
	pasz->Add("beforen");
	pasz->Add("beginn");
	pasz->Add("behaviorn");
	pasz->Add("behindn");
	pasz->Add("believen");
	pasz->Add("benefitn");
	pasz->Add("bestn");
	pasz->Add("bettern");
	pasz->Add("betweenn");
	pasz->Add("beyondn");
	pasz->Add("bign");
	pasz->Add("billn");
	pasz->Add("billionn");
	pasz->Add("bitn");
	pasz->Add("blackn");
	pasz->Add("bloodn");
	pasz->Add("bluen");
	pasz->Add("boardn");
	pasz->Add("bodyn");
	pasz->Add("bookn");
	pasz->Add("bornn");
	pasz->Add("bothn");
	pasz->Add("boxn");
	pasz->Add("boyn");
	pasz->Add("breakn");
	pasz->Add("bringn");
	pasz->Add("brothern");
	pasz->Add("budgetn");
	pasz->Add("buildn");
	pasz->Add("buildingn");
	pasz->Add("businessn");
	pasz->Add("butn");
	pasz->Add("buyn");
	pasz->Add("byn");
	pasz->Add("calln");
	pasz->Add("cameran");
	pasz->Add("campaignn");
	pasz->Add("cann");
	pasz->Add("cancern");
	pasz->Add("candidaten");
	pasz->Add("capitaln");
	pasz->Add("carn");
	pasz->Add("cardn");
	pasz->Add("caren");
	pasz->Add("careern");
	pasz->Add("carryn");
	pasz->Add("casen");
	pasz->Add("catchn");
	pasz->Add("causen");
	pasz->Add("celln");
	pasz->Add("centern");
	pasz->Add("centraln");
	pasz->Add("centuryn");
	pasz->Add("certainn");
	pasz->Add("certainlyn");
	pasz->Add("chairn");
	pasz->Add("challengen");
	pasz->Add("chancen");
	pasz->Add("changen");
	pasz->Add("charactern");
	pasz->Add("chargen");
	pasz->Add("checkn");
	pasz->Add("childn");
	pasz->Add("choicen");
	pasz->Add("choosen");
	pasz->Add("churchn");
	pasz->Add("citizenn");
	pasz->Add("cityn");
	pasz->Add("civiln");
	pasz->Add("claimn");
	pasz->Add("classn");
	pasz->Add("clearn");
	pasz->Add("clearlyn");
	pasz->Add("closen");
	pasz->Add("coachn");
	pasz->Add("coldn");
	pasz->Add("collectionn");
	pasz->Add("collegen");
	pasz->Add("colorn");
	pasz->Add("comen");
	pasz->Add("commercialn");
	pasz->Add("commonn");
	pasz->Add("communityn");
	pasz->Add("companyn");
	pasz->Add("comparen");
	pasz->Add("computern");
	pasz->Add("concernn");
	pasz->Add("conditionn");
	pasz->Add("conferencen");
	pasz->Add("Congressn");
	pasz->Add("considern");
	pasz->Add("consumern");
	pasz->Add("containn");
	pasz->Add("continuen");
	pasz->Add("controln");
	pasz->Add("costn");
	pasz->Add("couldn");
	pasz->Add("countryn");
	pasz->Add("couplen");
	pasz->Add("coursen");
	pasz->Add("courtn");
	pasz->Add("covern");
	pasz->Add("createn");
	pasz->Add("crimen");
	pasz->Add("culturaln");
	pasz->Add("culturen");
	pasz->Add("cupn");
	pasz->Add("currentn");
	pasz->Add("customern");
	pasz->Add("cutn");
	pasz->Add("darkn");
	pasz->Add("datan");
	pasz->Add("daughtern");
	pasz->Add("dayn");
	pasz->Add("deadn");
	pasz->Add("dealn");
	pasz->Add("deathn");
	pasz->Add("debaten");
	pasz->Add("decaden");
	pasz->Add("deciden");
	pasz->Add("decisionn");
	pasz->Add("deepn");
	pasz->Add("defensen");
	pasz->Add("degreen");
	pasz->Add("Democratn");
	pasz->Add("democraticn");
	pasz->Add("describen");
	pasz->Add("designn");
	pasz->Add("despiten");
	pasz->Add("detailn");
	pasz->Add("determinen");
	pasz->Add("developn");
	pasz->Add("developmentn");
	pasz->Add("dien");
	pasz->Add("differencen");
	pasz->Add("differentn");
	pasz->Add("difficultn");
	pasz->Add("dinnern");
	pasz->Add("directionn");
	pasz->Add("directorn");
	pasz->Add("discovern");
	pasz->Add("discussn");
	pasz->Add("discussionn");
	pasz->Add("diseasen");
	pasz->Add("don");
	pasz->Add("	doctorn");
	pasz->Add("	dogn");
	pasz->Add("	doorn");
	pasz->Add("	downn");
	pasz->Add("	drawn");
	pasz->Add("	dreamn");
	pasz->Add("	driven");
	pasz->Add("	dropn");
	pasz->Add("	drugn");
	pasz->Add("	duringn");
	pasz->Add("	eachn");
	pasz->Add("	earlyn");
	pasz->Add("	eastn");
	pasz->Add("	easyn");
	pasz->Add("	eatn");
	pasz->Add("	economicn");
	pasz->Add("	economyn");
	pasz->Add("	edgen");
	pasz->Add("	educationn");
	pasz->Add("	effectn");
	pasz->Add("	effortn");
	pasz->Add("	eightn");
	pasz->Add("	eithern");
	pasz->Add("	electionn");
	pasz->Add("elsen");
	pasz->Add("employeen");
	pasz->Add("endn");
	pasz->Add("energyn");
	pasz->Add("enjoyn");
	pasz->Add("enoughn");
	pasz->Add("entern");
	pasz->Add("entiren");
	pasz->Add("environmentn");
	pasz->Add("environmentaln");
	pasz->Add("especiallyn");
	pasz->Add("establishn");
	pasz->Add("evenn");
	pasz->Add("eveningn");
	pasz->Add("eventn");
	pasz->Add("evern");
	pasz->Add("everyn");
	pasz->Add("everybodyn");
	pasz->Add("everyonen");
	pasz->Add("everythingn");
	pasz->Add("evidencen");
	pasz->Add("exactlyn");
	pasz->Add("examplen");
	pasz->Add("executiven");
	pasz->Add("existn");
	pasz->Add("expectn");
	pasz->Add("experiencen");
	pasz->Add("expertn");
	pasz->Add("explainn");
	pasz->Add("eyen");
	pasz->Add("facen");
	pasz->Add("factn");
	pasz->Add("factorn");
	pasz->Add("failn");
	pasz->Add("falln");
	pasz->Add("familyn");
	pasz->Add("farn");
	pasz->Add("fastn");
	pasz->Add("fathern");
	pasz->Add("fearn");
	pasz->Add("federaln");
	pasz->Add("feeln");
	pasz->Add("feelingn");
	pasz->Add("fewn");
	pasz->Add("fieldn");
	pasz->Add("fightn");
	pasz->Add("figuren");
	pasz->Add("filln");
	pasz->Add("filmn");
	pasz->Add("finaln");
	pasz->Add("finallyn");
	pasz->Add("financialn");
	pasz->Add("findn");
	pasz->Add("finen");
	pasz->Add("fingern");
	pasz->Add("finishn");
	pasz->Add("firen");
	pasz->Add("firmn");
	pasz->Add("firstn");
	pasz->Add("fishn");
	pasz->Add("fiven");
	pasz->Add("floorn");
	pasz->Add("flyn");
	pasz->Add("focusn");
	pasz->Add("follown");
	pasz->Add("foodn");
	pasz->Add("footn");
	pasz->Add("forn");
	pasz->Add("forcen");
	pasz->Add("foreignn");
	pasz->Add("forgetn");
	pasz->Add("formn");
	pasz->Add("formern");
	pasz->Add("forwardn");
	pasz->Add("fourn");
	pasz->Add("freen");
	pasz->Add("friendn");
	pasz->Add("fromn");
	pasz->Add("frontn");
	pasz->Add("fulln");
	pasz->Add("fundn");
	pasz->Add("futuren");
	pasz->Add("gamen");
	pasz->Add("gardenn");
	pasz->Add("gasn");
	pasz->Add("generaln");
	pasz->Add("generationn");
	pasz->Add("getn");
	pasz->Add("girln");
	pasz->Add("given");
	pasz->Add("glassn");
	pasz->Add("gon");
	pasz->Add("goaln");
	pasz->Add("goodn");
	pasz->Add("governmentn");
	pasz->Add("greatn");
	pasz->Add("greenn");
	pasz->Add("groundn");
	pasz->Add("groupn");
	pasz->Add("grown");
	pasz->Add("growthn");
	pasz->Add("guessn");
	pasz->Add("gunn");
	pasz->Add("guyn");
	pasz->Add("hairn");
	pasz->Add("halfn");
	pasz->Add("handn");
	pasz->Add("hangn");
	pasz->Add("happenn");
	pasz->Add("happyn");
	pasz->Add("hardn");
	pasz->Add("haven");
	pasz->Add("hen");
	pasz->Add("headn");
	pasz->Add("healthn");
	pasz->Add("hearn");
	pasz->Add("heartn");
	pasz->Add("heatn");
	pasz->Add("heavyn");
	pasz->Add("helpn");
	pasz->Add("hern");
	pasz->Add("heren");
	pasz->Add("herselfn");
	pasz->Add("highn");
	pasz->Add("himn");
	pasz->Add("himselfn");
	pasz->Add("hisn");
	pasz->Add("historyn");
	pasz->Add("hitn");
	pasz->Add("holdn");
	pasz->Add("homen");
	pasz->Add("hopen");
	pasz->Add("hospitaln");
	pasz->Add("hotn");
	pasz->Add("hoteln");
	pasz->Add("hourn");
	pasz->Add("housen");
	pasz->Add("hown");
	pasz->Add("howevern");
	pasz->Add("hugen");
	pasz->Add("humann");
	pasz->Add("hundredn");
	pasz->Add("husbandn");
	pasz->Add("In");
	pasz->Add("idean");
	pasz->Add("identifyn");
	pasz->Add("ifn");
	pasz->Add("imagen");
	pasz->Add("imaginen");
	pasz->Add("impactn");
	pasz->Add("importantn");
	pasz->Add("improven");
	pasz->Add("inn");
	pasz->Add("includen");
	pasz->Add("includingn");
	pasz->Add("increasen");
	pasz->Add("indeedn");
	pasz->Add("indicaten");
	pasz->Add("individualn");
	pasz->Add("industryn");
	pasz->Add("informationn");
	pasz->Add("insiden");
	pasz->Add("insteadn");
	pasz->Add("institutionn");
	pasz->Add("interestn");
	pasz->Add("interestingn");
	pasz->Add("internationaln");
	pasz->Add("interviewn");
	pasz->Add("inton");
	pasz->Add("investmentn");
	pasz->Add("involven");
	pasz->Add("issuen");
	pasz->Add("itn");
	pasz->Add("itemn");
	pasz->Add("itsn");
	pasz->Add("itselfn");
	pasz->Add("jobn");
	pasz->Add("joinn");
	pasz->Add("justn");
	pasz->Add("keepn");
	pasz->Add("keyn");
	pasz->Add("kidn");
	pasz->Add("killn");
	pasz->Add("kindn");
	pasz->Add("kitchenn");
	pasz->Add("known");
	pasz->Add("knowledgen");
	pasz->Add("landn");
	pasz->Add("languagen");
	pasz->Add("largen");
	pasz->Add("lastn");
	pasz->Add("laten");
	pasz->Add("latern");
	pasz->Add("laughn");
	pasz->Add("lawn");
	pasz->Add("lawyern");
	pasz->Add("layn");
	pasz->Add("leadn");
	pasz->Add("leadern");
	pasz->Add("learnn");
	pasz->Add("leastn");
	pasz->Add("leaven");
	pasz->Add("leftn");
	pasz->Add("legn");
	pasz->Add("legaln");
	pasz->Add("lessn");
	pasz->Add("letn");
	pasz->Add("lettern");
	pasz->Add("leveln");
	pasz->Add("lien");
	pasz->Add("lifen");
	pasz->Add("lightn");
	pasz->Add("liken");
	pasz->Add("likelyn");
	pasz->Add("linen");
	pasz->Add("listn");
	pasz->Add("listenn");
	pasz->Add("littlen");
	pasz->Add("liven");
	pasz->Add("localn");
	pasz->Add("longn");
	pasz->Add("lookn");
	pasz->Add("losen");
	pasz->Add("lossn");
	pasz->Add("lotn");
	pasz->Add("loven");
	pasz->Add("lown");
	pasz->Add("machinen");
	pasz->Add("magazinen");
	pasz->Add("mainn");
	pasz->Add("maintainn");
	pasz->Add("majorn");
	pasz->Add("majorityn");
	pasz->Add("maken");
	pasz->Add("mann");
	pasz->Add("managen");
	pasz->Add("managementn");
	pasz->Add("managern");
	pasz->Add("manyn");
	pasz->Add("marketn");
	pasz->Add("marriagen");
	pasz->Add("materialn");
	pasz->Add("mattern");
	pasz->Add("mayn");
	pasz->Add("mayben");
	pasz->Add("men");
	pasz->Add("meann");
	pasz->Add("measuren");
	pasz->Add("median");
	pasz->Add("medicaln");
	pasz->Add("meetn");
	pasz->Add("meetingn");
	pasz->Add("membern");
	pasz->Add("memoryn");
	pasz->Add("mentionn");
	pasz->Add("messagen");
	pasz->Add("methodn");
	pasz->Add("middlen");
	pasz->Add("mightn");
	pasz->Add("militaryn");
	pasz->Add("millionn");
	pasz->Add("mindn");
	pasz->Add("minuten");
	pasz->Add("missn");
	pasz->Add("missionn");
	pasz->Add("modeln");
	pasz->Add("modernn");
	pasz->Add("momentn");
	pasz->Add("moneyn");
	pasz->Add("monthn");
	pasz->Add("moren");
	pasz->Add("morningn");
	pasz->Add("mostn");
	pasz->Add("mothern");
	pasz->Add("mouthn");
	pasz->Add("moven");
	pasz->Add("movementn");
	pasz->Add("movien");
	pasz->Add("Mrn");
	pasz->Add("Mrsn");
	pasz->Add("muchn");
	pasz->Add("musicn");
	pasz->Add("mustn");
	pasz->Add("myn");
	pasz->Add("myselfn");
	pasz->Add("namen");
	pasz->Add("nationn");
	pasz->Add("nationaln");
	pasz->Add("naturaln");
	pasz->Add("naturen");
	pasz->Add("nearn");
	pasz->Add("nearlyn");
	pasz->Add("necessaryn");
	pasz->Add("needn");
	pasz->Add("networkn");
	pasz->Add("nevern");
	pasz->Add("newn");
	pasz->Add("newsn");
	pasz->Add("newspapern");
	pasz->Add("nextn");
	pasz->Add("nicen");
	pasz->Add("nightn");
	pasz->Add("non");
	pasz->Add("nonen");
	pasz->Add("norn");
	pasz->Add("northn");
	pasz->Add("notn");
	pasz->Add("noten");
	pasz->Add("nothingn");
	pasz->Add("noticen");
	pasz->Add("nown");
	pasz->Add("n'tn");
	pasz->Add("numbern");
	pasz->Add("occurn");
	pasz->Add("ofn");
	pasz->Add("offn");
	pasz->Add("offern");
	pasz->Add("officen");
	pasz->Add("officern");
	pasz->Add("officialn");
	pasz->Add("oftenn");
	pasz->Add("ohn");
	pasz->Add("oiln");
	pasz->Add("okn");
	pasz->Add("oldn");
	pasz->Add("onn");
	pasz->Add("oncen");
	pasz->Add("onen");
	pasz->Add("onlyn");
	pasz->Add("onton");
	pasz->Add("openn");
	pasz->Add("operationn");
	pasz->Add("opportunityn");
	pasz->Add("optionn");
	pasz->Add("orn");
	pasz->Add("ordern");
	pasz->Add("organizationn");
	pasz->Add("othern");
	pasz->Add("othersn");
	pasz->Add("ourn");
	pasz->Add("outn");
	pasz->Add("outsiden");
	pasz->Add("overn");
	pasz->Add("ownn");
	pasz->Add("ownern");
	pasz->Add("pagen");
	pasz->Add("painn");
	pasz->Add("paintingn");
	pasz->Add("papern");
	pasz->Add("parentn");
	pasz->Add("partn");
	pasz->Add("participantn");
	pasz->Add("particularn");
	pasz->Add("particularlyn");
	pasz->Add("partnern");
	pasz->Add("partyn");
	pasz->Add("passn");
	pasz->Add("pastn");
	pasz->Add("patientn");
	pasz->Add("patternn");
	pasz->Add("payn");
	pasz->Add("peacen");
	pasz->Add("peoplen");
	pasz->Add("pern");
	pasz->Add("performn");
	pasz->Add("performancen");
	pasz->Add("perhapsn");
	pasz->Add("periodn");
	pasz->Add("personn");
	pasz->Add("personaln");
	pasz->Add("phonen");
	pasz->Add("physicaln");
	pasz->Add("pickn");
	pasz->Add("picturen");
	pasz->Add("piecen");
	pasz->Add("placen");
	pasz->Add("plann");
	pasz->Add("plantn");
	pasz->Add("playn");
	pasz->Add("playern");
	pasz->Add("PMn");
	pasz->Add("pointn");
	pasz->Add("policen");
	pasz->Add("policyn");
	pasz->Add("politicaln");
	pasz->Add("politicsn");
	pasz->Add("poorn");
	pasz->Add("popularn");
	pasz->Add("populationn");
	pasz->Add("positionn");
	pasz->Add("positiven");
	pasz->Add("possiblen");
	pasz->Add("powern");
	pasz->Add("practicen");
	pasz->Add("preparen");
	pasz->Add("presentn");
	pasz->Add("presidentn");
	pasz->Add("pressuren");
	pasz->Add("prettyn");
	pasz->Add("preventn");
	pasz->Add("pricen");
	pasz->Add("privaten");
	pasz->Add("probablyn");
	pasz->Add("problemn");
	pasz->Add("processn");
	pasz->Add("producen");
	pasz->Add("productn");
	pasz->Add("productionn");
	pasz->Add("professionaln");
	pasz->Add("professorn");
	pasz->Add("programn");
	pasz->Add("projectn");
	pasz->Add("propertyn");
	pasz->Add("protectn");
	pasz->Add("proven");
	pasz->Add("providen");
	pasz->Add("publicn");
	pasz->Add("pulln");
	pasz->Add("purposen");
	pasz->Add("pushn");
	pasz->Add("putn");
	pasz->Add("qualityn");
	pasz->Add("questionn");
	pasz->Add("quicklyn");
	pasz->Add("quiten");
	pasz->Add("racen");
	pasz->Add("radion");
	pasz->Add("raisen");
	pasz->Add("rangen");
	pasz->Add("raten");
	pasz->Add("rathern");
	pasz->Add("reachn");
	pasz->Add("readn");
	pasz->Add("readyn");
	pasz->Add("realn");
	pasz->Add("realityn");
	pasz->Add("realizen");
	pasz->Add("reallyn");
	pasz->Add("reasonn");
	pasz->Add("receiven");
	pasz->Add("recentn");
	pasz->Add("recentlyn");
	pasz->Add("recognizen");
	pasz->Add("recordn");
	pasz->Add("redn");
	pasz->Add("reducen");
	pasz->Add("reflectn");
	pasz->Add("regionn");
	pasz->Add("relaten");
	pasz->Add("relationshipn");
	pasz->Add("religiousn");
	pasz->Add("remainn");
	pasz->Add("remembern");
	pasz->Add("removen");
	pasz->Add("reportn");
	pasz->Add("representn");
	pasz->Add("Republicann");
	pasz->Add("requiren");
	pasz->Add("researchn");
	pasz->Add("resourcen");
	pasz->Add("respondn");
	pasz->Add("responsen");
	pasz->Add("responsibilityn");
	pasz->Add("restn");
	pasz->Add("resultn");
	pasz->Add("returnn");
	pasz->Add("revealn");
	pasz->Add("richn");
	pasz->Add("rightn");
	pasz->Add("risen");
	pasz->Add("riskn");
	pasz->Add("roadn");
	pasz->Add("rockn");
	pasz->Add("rolen");
	pasz->Add("roomn");
	pasz->Add("rulen");
	pasz->Add("runn");
	pasz->Add("safen");
	pasz->Add("samen");
	pasz->Add("saven");
	pasz->Add("sayn");
	pasz->Add("scenen");
	pasz->Add("schooln");
	pasz->Add("sciencen");
	pasz->Add("scientistn");
	pasz->Add("scoren");
	pasz->Add("sean");
	pasz->Add("seasonn");
	pasz->Add("seatn");
	pasz->Add("secondn");
	pasz->Add("sectionn");
	pasz->Add("securityn");
	pasz->Add("seen");
	pasz->Add("seekn");
	pasz->Add("seemn");
	pasz->Add("selln");
	pasz->Add("sendn");
	pasz->Add("seniorn");
	pasz->Add("sensen");
	pasz->Add("seriesn");
	pasz->Add("seriousn");
	pasz->Add("serven");
	pasz->Add("servicen");
	pasz->Add("setn");
	pasz->Add("sevenn");
	pasz->Add("severaln");
	pasz->Add("sexn");
	pasz->Add("sexualn");
	pasz->Add("shaken");
	pasz->Add("sharen");
	pasz->Add("shen");
	pasz->Add("shootn");
	pasz->Add("shortn");
	pasz->Add("shotn");
	pasz->Add("shouldn");
	pasz->Add("shouldern");
	pasz->Add("shown");
	pasz->Add("siden");
	pasz->Add("signn");
	pasz->Add("significantn");
	pasz->Add("similarn");
	pasz->Add("simplen");
	pasz->Add("simplyn");
	pasz->Add("sincen");
	pasz->Add("singn");
	pasz->Add("singlen");
	pasz->Add("sistern");
	pasz->Add("sitn");
	pasz->Add("siten");
	pasz->Add("situationn");
	pasz->Add("sixn");
	pasz->Add("sizen");
	pasz->Add("skilln");
	pasz->Add("skinn");
	pasz->Add("smalln");
	pasz->Add("smilen");
	pasz->Add("son");
	pasz->Add("socialn");
	pasz->Add("societyn");
	pasz->Add("soldiern");
	pasz->Add("somen");
	pasz->Add("somebodyn");
	pasz->Add("someonen");
	pasz->Add("somethingn");
	pasz->Add("sometimesn");
	pasz->Add("sonn");
	pasz->Add("songn");
	pasz->Add("soonn");
	pasz->Add("sortn");
	pasz->Add("soundn");
	pasz->Add("sourcen");
	pasz->Add("southn");
	pasz->Add("southernn");
	pasz->Add("spacen");
	pasz->Add("speakn");
	pasz->Add("specialn");
	pasz->Add("specificn");
	pasz->Add("speechn");
	pasz->Add("spendn");
	pasz->Add("sportn");
	pasz->Add("springn");
	pasz->Add("staffn");
	pasz->Add("stagen");
	pasz->Add("standn");
	pasz->Add("standardn");
	pasz->Add("starn");
	pasz->Add("startn");
	pasz->Add("staten");
	pasz->Add("statementn");
	pasz->Add("stationn");
	pasz->Add("stayn");
	pasz->Add("stepn");
	pasz->Add("stilln");
	pasz->Add("stockn");
	pasz->Add("stopn");
	pasz->Add("storen");
	pasz->Add("storyn");
	pasz->Add("strategyn");
	pasz->Add("streetn");
	pasz->Add("strongn");
	pasz->Add("structuren");
	pasz->Add("studentn");
	pasz->Add("studyn");
	pasz->Add("stuffn");
	pasz->Add("stylen");
	pasz->Add("subjectn");
	pasz->Add("successn");
	pasz->Add("successfuln");
	pasz->Add("suchn");
	pasz->Add("suddenlyn");
	pasz->Add("suffern");
	pasz->Add("suggestn");
	pasz->Add("summern");
	pasz->Add("supportn");
	pasz->Add("suren");
	pasz->Add("surfacen");
	pasz->Add("systemn");
	pasz->Add("tablen");
	pasz->Add("taken");
	pasz->Add("talkn");
	pasz->Add("taskn");
	pasz->Add("taxn");
	pasz->Add("teachn");
	pasz->Add("teachern");
	pasz->Add("teamn");
	pasz->Add("technologyn");
	pasz->Add("televisionn");
	pasz->Add("telln");
	pasz->Add("tenn");
	pasz->Add("tendn");
	pasz->Add("termn");
	pasz->Add("testn");
	pasz->Add("thann");
	pasz->Add("thankn");
	pasz->Add("thatn");
	pasz->Add("then");
	pasz->Add("theirn");
	pasz->Add("themn");
	pasz->Add("themselvesn");
	pasz->Add("thenn");
	pasz->Add("theoryn");
	pasz->Add("theren");
	pasz->Add("thesen");
	pasz->Add("theyn");
	pasz->Add("thingn");
	pasz->Add("thinkn");
	pasz->Add("thirdn");
	pasz->Add("thisn");
	pasz->Add("thosen");
	pasz->Add("thoughn");
	pasz->Add("thoughtn");
	pasz->Add("thousandn");
	pasz->Add("threatn");
	pasz->Add("threen");
	pasz->Add("throughn");
	pasz->Add("throughoutn");
	pasz->Add("thrown");
	pasz->Add("thusn");
	pasz->Add("timen");
	pasz->Add("ton");
	pasz->Add("todayn");
	pasz->Add("togethern");
	pasz->Add("tonightn");
	pasz->Add("toon");
	pasz->Add("topn");
	pasz->Add("totaln");
	pasz->Add("toughn");
	pasz->Add("towardn");
	pasz->Add("townn");
	pasz->Add("traden");
	pasz->Add("traditionaln");
	pasz->Add("trainingn");
	pasz->Add("traveln");
	pasz->Add("treatn");
	pasz->Add("treatmentn");
	pasz->Add("treen");
	pasz->Add("trialn");
	pasz->Add("tripn");
	pasz->Add("troublen");
	pasz->Add("truen");
	pasz->Add("truthn");
	pasz->Add("tryn");
	pasz->Add("turnn");
	pasz->Add("TVn");
	pasz->Add("twon");
	pasz->Add("typen");
	pasz->Add("undern");
	pasz->Add("understandn");
	pasz->Add("unitn");
	pasz->Add("untiln");
	pasz->Add("upn");
	pasz->Add("uponn");
	pasz->Add("usn");
	pasz->Add("usen");
	pasz->Add("usuallyn");
	pasz->Add("valuen");
	pasz->Add("variousn");
	pasz->Add("veryn");
	pasz->Add("victimn");
	pasz->Add("viewn");
	pasz->Add("violencen");
	pasz->Add("visitn");
	pasz->Add("voicen");
	pasz->Add("voten");
	pasz->Add("waitn");
	pasz->Add("walkn");
	pasz->Add("walln");
	pasz->Add("wantn");
	pasz->Add("warn");
	pasz->Add("watchn");
	pasz->Add("watern");
	pasz->Add("wayn");
	pasz->Add("wen");
	pasz->Add("weaponn");
	pasz->Add("wearn");
	pasz->Add("weekn");
	pasz->Add("weightn");
	pasz->Add("welln");
	pasz->Add("westn");
	pasz->Add("westernn");
	pasz->Add("whatn");
	pasz->Add("whatevern");
	pasz->Add("whenn");
	pasz->Add("wheren");
	pasz->Add("whethern");
	pasz->Add("whichn");
	pasz->Add("whilen");
	pasz->Add("whiten");
	pasz->Add("whon");
	pasz->Add("wholen");
	pasz->Add("whomn");
	pasz->Add("whosen");
	pasz->Add("whyn");
	pasz->Add("widen");
	pasz->Add("wifen");
	pasz->Add("willn");
	pasz->Add("winn");
	pasz->Add("windn");
	pasz->Add("windown");
	pasz->Add("wishn");
	pasz->Add("withn");
	pasz->Add("withinn");
	pasz->Add("withoutn");
	pasz->Add("womann");
	pasz->Add("wondern");
	pasz->Add("wordn");
	pasz->Add("workn");
	pasz->Add("workern");
	pasz->Add("worldn");
	pasz->Add("worryn");
	pasz->Add("wouldn");
	pasz->Add("writen");
	pasz->Add("writern");
	pasz->Add("wrongn");
	pasz->Add("yardn");
	pasz->Add("yeahn");
	pasz->Add("yearn");
	pasz->Add("yesn");
	pasz->Add("yetn");
	pasz->Add("youn");
	pasz->Add("young");
	pasz->Add("your");
	pasz->Add("yourself");
}



//////////////////////////////////////////////////////////////////////////
//
//
//////////////////////////////////////////////////////////////////////////
void WordsInit(void)
{
	gaszArchaicWords.Init();
	gaszArchaicDefinitions.Init();
	gaszCommonWords.Init();

	GetArchaicDefinitions(&gaszArchaicDefinitions);
	GetArchaicWords(&gaszArchaicWords);
	GetCommonWords(&gaszCommonWords);
}


//////////////////////////////////////////////////////////////////////////
//
//
//////////////////////////////////////////////////////////////////////////
void WordsKill(void)
{
	gaszArchaicWords.Kill();
	gaszArchaicDefinitions.Kill();
	gaszCommonWords.Kill();
}

