#ifndef __PRIMITIVE_INTEGER_H__
#define __PRIMITIVE_INTEGER_H__
#include "BaseLib/Logger.h"
#include "Primitive.h"


PRIMITIVE_TYPE_DEFINITION(Int8, int8, PT_char)
PRIMITIVE_TYPE_DEFINITION(UInt8, uint8, PT_uchar)

PRIMITIVE_TYPE_DEFINITION(Int16, int16, PT_short)
PRIMITIVE_TYPE_DEFINITION(UInt16, uint16, PT_ushort)

PRIMITIVE_TYPE_DEFINITION(Int32, int32, PT_int)
PRIMITIVE_TYPE_DEFINITION(UInt32, uint32, PT_uint)

PRIMITIVE_TYPE_DEFINITION(Int64, int64, PT_long)
PRIMITIVE_TYPE_DEFINITION(UInt64, uint64, PT_ulong)

PRIMITIVE_TYPE_DEFINITION(Bool, int32, PT_bool)


#endif // __PRIMITIVE_INTEGER_H__

