#ifndef __OBJECT_FILE_GENERAL__
#define __OBJECT_FILE_GENERAL__


#define OBJECT_FILE_EXTENSION	"DRG"
#define BASIC_OBJECT_FILE	1
#define CHUNKED_OBJECT_FILE	2

#define OBJECT_POINTER_NULL		'V'
#define OBJECT_POINTER_ID		'O'
#define OBJECT_POINTER_NAMED	'N'


#endif // __OBJECT_FILE_GENERAL__

