#ifndef __OBJECT_FILE_GENERAL__
#define __OBJECT_FILE_GENERAL__


#define OBJECT_FILE_EXTENSION	"DRG"
#define BASIC_OBJECT_FILE	'\0SAB'
#define CHUNKED_OBJECT_FILE	'\0KHC'

#define OBJECT_POINTER_NULL		'\0LUN'
#define OBJECT_POINTER_ID		'\0XDI'
#define OBJECT_POINTER_NAMED	'\0MAN'


#endif // __OBJECT_FILE_GENERAL__

